export const Drinks_Avaible = [
    {
        id: 'drink1',
        name: 'Coca-Cola Classic 2 lts',
        description: 'Coca-Cola Clasicc 2lts',
        picture: 'https://s3-symbol-logo.tradingview.com/coca-cola--600.png',
        price: 199.99,
      },
      {
        id: 'drink2',
        name: 'Coca-Cola Classic 600 ml',
        description: 'Coca-Cola Clasicc 600 ml',
        picture: 'https://s3-symbol-logo.tradingview.com/coca-cola--600.png',
        price: 199.99,
      },
      {
        id: 'drink3',
        name: 'Pepsi Classic 2lts',
        description: 'Pepsi Classic 2lts',
        picture: 'https://lh3.googleusercontent.com/proxy/SzOlgoYv7Y6KtQDa5wwz1kFHD4jJMfQcG-FGfx3HYBPNX7LRNGMMecnSXfKQzeTDhti-Oj8RgohT2WWL56x4eFqD0ZUESgBntwDEUUgVikFlJhe_RQ',
        price: 179.99,
      },
      {
        id: 'drink4',
        name: 'Pepsi Classic 600 ml',
        description: 'Pepsi Classic 600 ml',
        picture: 'https://lh3.googleusercontent.com/proxy/SzOlgoYv7Y6KtQDa5wwz1kFHD4jJMfQcG-FGfx3HYBPNX7LRNGMMecnSXfKQzeTDhti-Oj8RgohT2WWL56x4eFqD0ZUESgBntwDEUUgVikFlJhe_RQ',
        price: 179.99,
      },
      {
        id: 'drink5',
        name: 'Seven Up 2lts',
        description: 'Seven Up 2lts',
        picture: 'https://media.designrush.com/inspirations/129767/conversions/_1528381466_147_7up-preview.jpg',
        price: 199.99,
      },
      {
        id: 'drink6',
        name: 'Seven Up 600 ml',
        description: 'Seven Up 600 ml',
        picture: 'https://media.designrush.com/inspirations/129767/conversions/_1528381466_147_7up-preview.jpg',
        price: 199.99,
      },
      {
        id: 'drink7',
        name: 'Fanta 2lts',
        description: 'Fanta 2lts',
        picture: 'http://3.bp.blogspot.com/-2SPS7XwNC60/UB6iqkjdn8I/AAAAAAAAFrE/lJnDYB64km4/s1600/fanta9.jpg',
        price: 199.99,    
    },
    {
        id: 'drink8',
        name: 'Fanta 600 ml',
        description: 'Fanta 600 ml',
        picture: 'http://3.bp.blogspot.com/-2SPS7XwNC60/UB6iqkjdn8I/AAAAAAAAFrE/lJnDYB64km4/s1600/fanta9.jpg',
        price: 199.99,    
    },
    {
        id: 'drink9',
        name: 'Sidral Mundet 2lts',
        description: 'Sidral Mundet 2lts',
        picture: 'http://www.elpublicista.info/wp-content/uploads/2017/06/Sidral.png',
        price: 199.99,    
    },
    {
        id: 'drink10',
        name: 'Sidral Mundet 600 ml',
        description: 'Sidral Mundet 600 ml',
        picture: 'http://www.elpublicista.info/wp-content/uploads/2017/06/Sidral.png',
        price: 199.99,    
    }
]